### ISSUE TITLE
output format

### ISSUE THREAD

**Issue by chikashimiyama** [pd-externals/hoalight#12]
vbap uses output format like

"speaker-number level" "speaker-number level"...

<img width="166" alt="Screenshot 2021-03-29 at 12 03 28" src="https://user-images.githubusercontent.com/3512188/112821298-caf4f280-9086-11eb-90f4-cf86c238921a.png">

should I change the output of hoa like this (it currently outputs just one list)

**Comment by danomatika** [comment]
Yeah. Parsing a list when the speaker setups will be variable is harder in the server patch, so making it match vbap is what is needed.

**Comment by chikashimiyama** [comment]
f73cd0ba90fb1a8e659273cc421987b07580e122 solved this
